### ISSUE TITLE
A question about Grounded videoQA submission

### ISSUE THREAD

**Issue by zhl98** [deepmind/perception_test#5]
Hello,

I saw that other issues mentioned the need to submit predictions for all frames during the testing phase. However, I encountered an error after submitting it. Can you help me solve it?

 
<img width="812" alt="image" src="https://github.com/deepmind/perception_test/assets/51871747/6a2e5f8a-954c-4011-8267-5f0d189d48ed">

**Comment by ptchallenge-workshop** [comment]
Hi,

This was due to a bug in the code that we have now fixed. Sorry for the confusion, as the challenge states for any object track please submit for all frames in the video where the object is tracked.

It's OK if there are frames missing due to occlusion etc, as long as the number of frame IDs matches the number of bounding boxes for a given track.

**Comment by zhl98** [comment]
Ok. Thank you.
